version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: surge
    main: .
    ldflags:
      - -s -w 
      - -X github.com/SurgeDM/Surge/cmd.Version={{.Version}}
      - -X github.com/SurgeDM/Surge/cmd.Commit={{.Commit}}
      - -X github.com/SurgeDM/Surge/cmd.BuildTime={{.Date}}

before:
  hooks:
    - ./scripts/package-fonts.sh
    - ./scripts/package-themes.sh

changelog:
  sort: asc

  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

